export const TEAM = {
  'ATL':{code:'ATL',city:'Atlanta',name:'Hawks',division:'Southeast', conference:'Eastern', color:"#E13A3E" },
	'BKN':{code:'BKN',city:'Brooklyn',name:'Nets',division:'Atlantic', conference:'Eastern', color:"#000000"},
	'BOS':{code:'BOS',city:'Boston',name:'Celtics',division:'Atlantic', conference:'Eastern', color:"#007239"},
	'CHA':{code:'CHA',city:'Charlotte',name:'Hornets',division:'Southeast', conference:'Eastern', color:"#1D1160"},
	'CHI':{code:'CHI',city:'Chicago',name:'Bulls',division:'Central', conference:'Eastern', color:"#C60033"},
	'CLE':{code:'CLE',city:'Cleveland',name:'Cavaliers',division:'Central', conference:'Eastern', color:"#B2004A"},
	'DAL':{code:'DAL',city:'Dallas',name:'Mavericks',division:'Southwest', conference:'Western', color:"#0063AF"},
	'DEN':{code:'DEN',city:'Denver',name:'Nuggets',division:'Northwest', conference:'Western', color:"#559FD6"},
	'DET':{code:'DET',city:'Detroit',name:'Pistons',division:'Central', conference:'Eastern', color:"#EC003D"},
	'GSW':{code:'GSW',city:'Golden State',name:'Warriors',division:'Pacific', conference:'Western', color:"#0068B3"},
	'HOU':{code:'HOU',city:'Houston',name:'Rockets',division:'Southwest', conference:'Western', color:"#C60033"},
	'IND':{code:'IND',city:'Indiana',name:'Pacers',division:'Central', conference:'Eastern', color:"#FFC633"},
	'LAC':{code:'LAC',city:'LA',name:'Clippers',division:'Pacific', conference:'Western', color:"#006BB6"},
	'LAL':{code:'LAL',city:'Los Angeles',name:'Lakers',division:'Pacific', conference:'Western', color:"#FEA927"},
	'MEM':{code:'MEM',city:'Memphis',name:'Grizzlies',division:'Southwest', conference:'Western', color:"#bed4e9"},
	'MIA':{code:'MIA',city:'Miami',name:'Heat',division:'Southeast', conference:'Eastern', color:"#98002E"},
	'MIL':{code:'MIL',city:'Milwaukee',name:'Bucks',division:'Central', conference:'Eastern', color:"#00471B"},
	'MIN':{code:'MIN',city:'Minnesota',name:'Timberwolves',division:'Northwest', conference:'Western', color:"#3B6A8E"},
	'NJN':{code:'NJN',city:'New Jersey',name:'Nets',division:'', conference:'', color:"#C60033"},
	'NOH':{code:'NOH',city:'New Orleans',name:'Hornets',division:'', conference:'', color:"#008FC5"},
	'NOP':{code:'NOP',city:'New Orleans',name:'Pelicans',division:'Southwest', conference:'Western', color:"#002B5C"},
	'NYK':{code:'NYK',city:'New York',name:'Knicks',division:'Atlantic', conference:'Eastern', color:"#F3571F"},
	'OKC':{code:'OKC',city:'Oklahoma City',name:'Thunder',division:'Northwest', conference:'Western', color:"#FDBB30"},
	'ORL':{code:'ORL',city:'Orlando',name:'Magic',division:'Southeast', conference:'Eastern', color:"#006BB7"},
	'PHI':{code:'PHI',city:'Philadelphia',name:'76ers',division:'Atlantic', conference:'Eastern', color:"#EC003D"},
	'PHX':{code:'PHX',city:'Phoenix',name:'Suns',division:'Pacific', conference:'Western', color:"#E4491D"},
	'POR':{code:'POR',city:'Portland',name:'Trailblazers',division:'Northwest', conference:'Western', color:"#DE2032"},
	'SAC':{code:'SAC',city:'Sacramento',name:'Kings',division:'Pacific', conference:'Western', color:"#5B2B82"},
	'SAS':{code:'SAS',city:'San Antonio',name:'Spurs',division:'Southwest', conference:'Western', color:"#BAC4CA"},
	'TOR':{code:'TOR',city:'Toronto',name:'Raptors',division:'Atlantic', conference:'Eastern', color:"#CE1141"},
	'UTA':{code:'UTA',city:'Utah',name:'Jazz',division:'Northwest', conference:'Western', color:"#002B5C"},
	'WAS':{code:'WAS',city:'Washington',name:'Wizards',division:'Southeast', conference:'Eastern', color:"#E21836"},
	'EST':{code:'EST',city:'All-Star',name:'East',division:'', conference:'', color:"#00559A"},
	'WST':{code:'WST',city:'All-Star',name:'West',division:'', conference:'', color:"#EC003D"},
	'CHK':{code:'CHK',city:'Rising Stars',name:'Team Chuck',division:'', conference:'', color:"#FCB034"},
	'SHQ':{code:'SHQ',city:'Rising Stars',name:'Team Shaq',division:'', conference:'', color:"#0077C0"},
	'HIL':{code:'HIL',city:'Rising Stars',name:'Team Hill',division:'', conference:'', color:"#FBAF33"},
	'WEB':{code:'WEB',city:'Rising Stars',name:'Team Webber',division:'', conference:'', color:"#00529B"},
	'USA':{code:'USA',city:'Rising Stars',name:'Team USA',division:'', conference:'', color:"#8A8C8E"},
	//'USA':{code:'USA',city:'USA',name:'USA',division:'', conference:'', color:"#012539"},
	//'WLD':{code:'WLD',city:'Rising Stars',name:'Team World',division:'', conference:'', color:"#051922"},
	'WLD':{code:'WLD',city:'World',name:'Team World',division:'', conference:'', color:"#F1B80F"},
	'ACC':{code:'ACC',city:'Celebrity',name:'Canada',division:'', conference:'', color:"#EC003D"},
	'ACU':{code:'ACU',city:'Celebrity',name:'USA',division:'', conference:'', color:"#00559A"},
	'ALB':{code:'ALB',city:'Berlin',name:'ALBA',division:'', conference:'', color:"#0063AF", isintl:true},
	'EAM':{code:'EAM',city:'Milan',name:'EA7',division:'', conference:'', color:"#000000", isintl:true},
	'FBU':{code:'FBU',city:'Istanbul',name:'Fenerbahce Ulker',division:'', conference:'', color:"#ED1940", isintl:true},
	'MPS':{code:'MPS',city:'Siena',name:'Montepaschi Siena',division:'', conference:'', color:"#007239", isintl:true},
	'RMD':{code:'RMD',city:'Madrid',name:'Real Madrid',division:'', conference:'', color:"#006BB7", isintl:true},
	'FCB':{code:'FCB',city:'Barcelona',name:'FC Barcelona',division:'', conference:'', color:"#446893", isintl:true},
	'MAC':{code:'MAC',city:'Haifa',name:'Maccabi Haifa',division:'', conference:'', color:"#155D30", isintl:true},
	'UBB':{code:'UBB',city:'Bilbao',name:'Bilbao Basket',division:'', conference:'', color:"#808284", isintl:true},
	'MOS':{code:'MOS',city:'Moscow',name:'CSKA Moscow',division:'', conference:'', color:"#023E88", isintl:true},
	'DLS':{code:'DLS',city:'G League',name:'G League Select',division:'', conference:'', color:"#ED174C", isintl:true},
	'MTA':{code:'MTA',city:'Tel Aviv',name:'Maccabi Electra',division:'', conference:'', color:"#0281B6", isintl:true},
	'FLA':{code:'FLA',city:'Flamengo',name:'Flamengo',division:'', conference:'', color:"#D13138", isintl:true},
	'CHB':{code:'CHB',city:'Charlotte',name:'Bobcats',division:'', conference:'', color:"#F24D28"},
	'ORB':{code:'ORB',city:'Orlando',name:'Magic Blue',division:'', conference:'', color:"#006BB7"},
	'ORW':{code:'ORW',city:'Orlando',name:'Magic White',division:'', conference:'', color:"#006BB7"},
	'ATW':{code:'ATW',city:'World',name:'Team World',division:'', conference:'', color:"#F1B80F", isintl:true},
	'ATA':{code:'ATA',city:'Africa',name:'Team Africa',division:'', conference:'', color:"#10A44B", isintl:true},
	'USB':{code:'USB',city:'USAB',name:'USAB Blue',division:'', conference:'', color:"#E21836"},
	'USW':{code:'USW',city:'USAB',name:'USAB White',division:'', conference:'', color:"#E21836"},
	'MLN':{code:'MLN',city:'Milano',name:'Olimpia Milano',division:'', conference:'', color:"#E31D1A", isintl:true},
	'BAU':{code:'BAU',city:'Bauru',name:'Paschoalotto/Bauru',division:'', conference:'', color:"#0E9E48", isintl:true},
	'CHN':{code:'CHN',city:'China',name:'China',division:'', conference:'', color:"#E40013", isintl:true},
	'ARG':{code:'ARG',city:'Argentina',name:'Argentina',division:'', conference:'', color:"#9EDBF6", isintl:true},
	'VEN':{code:'VEN',city:'Venezuela',name:'Venezuela',division:'', conference:'', color:"#6E1200", isintl:true},
	'NGR':{code:'NGR',city:'Nigeria',name:'Nigeria',division:'', conference:'', color:"#166645", isintl:true},
	'SDS':{code:'SDS',city:'Shanghai',name:'Sharks',division:'', conference:'', color:"#AF2B2E", isintl:true},
	'SLA':{code:'SLA',city:'San Lorenzo',name:'San Lorenzo',division:'', conference:'', color:"#005096", isintl:true},
	'AFR':{code:'AFR',city:'Africa',name:'Team Africa',division:'', conference:'', color:"#10A44B", isintl:true},
	'BNE':{code:'BNE',city:'Brisbane',name:'Bullets',division:'', conference:'', color:"#002D73", isintl:true},
	'MEL':{code:'MEL',city:'Melbourne',name:'United',division:'', conference:'', color:"#1C1F2A", isintl:true},
	'SYD':{code:'SYD',city:'Sydney',name:'Kings',division:'', conference:'', color:"#5B4097", isintl:true},
	'GUA':{code:'GUA',city:'Guangzhou',name:'Long-Lions',division:'', conference:'', color:"#151F42", isintl:true}
}

export const REGIONS = {
  "US": "1",
	"CA": "2",
	"AR": "6",
	"HK": "7",
	"CN": "8",
	"AU": "9",
	"BE": "10",
	"BR": "11",
	"DO": "12",
	"FR": "21",
	"DE": "14",
	"GR": "15",
	"IN": "16",
	"ID": "17",
	"IL": "18",
	"IT": "19",
	"JP": "20",
	"KR": "21",
	"MX": "22",
	"NL": "23",
	"AO": "24",
	"BJ": "24",
	"BW": "24",
	"BF": "24",
	"BI": "24",
	"AM": "24",
	"CF": "24",
	"KM": "24",
	"CG": "24",
	"CI": "24",
	"CD": "24",
	"GQ": "24",
	"ER": "24",
	"ET": "24",
	"GA": "24",
	"GM": "24",
	"GH": "24",
	"GN": "24",
	"GW": "24",
	"KE": "24",
	"LS": "24",
	"LR": "24",
	"MG": "24",
	"MW": "24",
	"ML": "24",
	"MU": "24",
	"YT": "24",
	"MZ": "24",
	"NA": "24",
	"NE": "24",
	"NG": "24",
	"RE": "24",
	"RW": "24",
	"ST": "24",
	"SN": "24",
	"SC": "24",
	"SL": "24",
	"SH": "24",
	"SZ": "24",
	"TZ": "24",
	"TG": "24",
	"UG": "24",
	"ZM": "24",
	"ZW": "24",
	"DZ": "25",
	"BH": "25",
	"TD": "25",
	"DJ": "25",
	"EG": "25",
	"IR": "25",
	"IQ": "25",
	"JO": "25",
	"KW": "25",
	"LB": "25",
	"LY": "25",
	"MR": "25",
	"MA": "25",
	"OM": "25",
	"PS": "25",
	"QA": "25",
	"SA": "25",
	"SO": "25",
	"SD": "25",
	"SY": "25",
	"TN": "25",
	"AE": "25",
	"YE": "25",
	"PH": "26",
	"PL": "27",
	"PT": "28",
	"CY": "29",
	"RU": "30",
	"ES": "31",
	"TW": "32",
	"TR": "33",
	"GB": "34",
	"VE": "35",
	"BA": "36",
	"BZ": "37",
	"BO": "37",
	"CL": "37",
	"CO": "37",
	"CR": "37",
	"EC": "37",
	"SV": "37",
	"FK": "37",
	"GF": "37",
	"GT": "37",
	"GY": "37",
	"HN": "37",
	"PA": "37",
	"PY": "37",
	"PE": "37",
	"SR": "37",
	"UY": "37",
	"AI": "38",
	"AG": "38",
	"AW": "38",
	"BS": "38",
	"BB": "38",
	"BM": "38",
	"VG": "38",
	"KY": "38",
	"CU": "38",
	"CW": "38",
	"DM": "38",
	"GD": "38",
	"GP": "38",
	"HT": "38",
	"JM": "38",
	"MQ": "38",
	"MS": "38",
	"BQ": "38",
	"BL": "38",
	"KN": "38",
	"LC": "38",
	"MF": "38",
	"VC": "38",
	"TT": "38",
	"TC": "38",
	"NI": "39", // FIXME 39 or 37? it also belongs to Pan-Latin America
	"ZA": "40", // FIXME 24 or 40? it also belongs to Pan-Africa
	"NZ": "41",
	"MN": "42",
	"SG": "43",
	"TH": "44",
	"MY": "45",
	"SE": "46",
	"FI": "47",
	"NO": "48"
}
